# trackball_arrow_processor.yaml
description: Custom input processor that maps trackball movement to arrow key presses
compatible: "custom,trackball-arrow-processor"
include: 
  - input-processor-base.yaml

properties:
  "#input-processor-cells":
    const: 0
